// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Porte.CaseStudy.Models;

namespace Porte.CaseStudy.Migrations
{
    [DbContext(typeof(PorteDBContext))]
    partial class PorteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Porte.CaseStudy.Models.Box", b =>
                {
                    b.Property<int>("BOX_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PART_COUNT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WEIGHT")
                        .HasColumnType("INTEGER");

                    b.HasKey("BOX_ID");

                    b.ToTable("Boxs");

                    b.HasData(
                        new
                        {
                            BOX_ID = 123450,
                            PART_COUNT = 1,
                            WEIGHT = 3
                        },
                        new
                        {
                            BOX_ID = 123461,
                            PART_COUNT = 1,
                            WEIGHT = 8
                        },
                        new
                        {
                            BOX_ID = 123472,
                            PART_COUNT = 1,
                            WEIGHT = 11
                        },
                        new
                        {
                            BOX_ID = 123483,
                            PART_COUNT = 1,
                            WEIGHT = 3
                        },
                        new
                        {
                            BOX_ID = 123494,
                            PART_COUNT = 1,
                            WEIGHT = 13
                        });
                });

            modelBuilder.Entity("Porte.CaseStudy.Models.Part", b =>
                {
                    b.Property<int>("PART_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BOX_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PART_COST")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PART_NUMBER")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PART_WEIGHT")
                        .HasColumnType("INTEGER");

                    b.HasKey("PART_ID");

                    b.ToTable("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
